version: '3.2'
services:
  sonarqube:
    build:
      context: sonarqube/
    ports:
      - 9000:9000
    container_name: sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresdb:5432/sonar
    volumes:
      - ./data/sonar/sonarqube/conf:/opt/sonarqube/conf
      - ./data/sonar/sonarqube/data:/opt/sonarqube/data
      - ./data/sonar/sonarqube/extensions:/opt/sonarqube/extensions

  postgresdb:
    build:
      context: postgres/
    #image: postgres
    container_name: postgresdb
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./data/postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - ./data/postgresql_data:/var/lib/postgresql/data

  jenkins:
    build:
      context: jenkins/
    privileged: true
    user: root
    ports:
      - 8090:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./data/jenkins:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_PATH}:/usr/bin/docker:ro
    depends_on:
      - sonarqube


networks: 
  default:
    external:
      name: dd_ninja